apiVersion: v1
kind: Service
metadata:
  name: db-seeder
  namespace: default
  labels:
    app: db-seeder
spec:
  ports:
    - name: db-seeder
      port: 80
      targetPort: 8032
      protocol: TCP
  selector:
    app: db-seeder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-seeder
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-seeder
  template:
    metadata:
      labels:
        app: db-seeder
    spec:
      containers:
        - name: db-seeder
          image: rejdeboer/mmo-db-seeder:latest # {"$imagepolicy": "flux-system:db-seeder"}
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8032
          env:
            - name: SEEDER_DATABASE_PORT
              value: "5432"
            - name: SEEDER_DATABASE_NAME
              value: "mmo"
            - name: SEEDER_DATABASE_HOST
              value: "postgres-main-rw"
            - name: SEEDER_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: SEEDER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: db-seeder
  namespace: default
spec:
  # entryPoints:
  #   - websecure # Assumes you are using the 'websecure' entrypoint for HTTPS
  routes:
  - match: Host(`db-seeder.homelab.io`)
    kind: Rule
    services:
    - name: db-seeder 
      port: 80
  # tls:
  #   certResolver: letsencrypt 
  #   domains:
  #   - main: "db-seeder.homelab.io"

