apiVersion: v1
kind: ConfigMap
metadata:
  name: game-server-config
  namespace: default
data:
  ENVIRONMENT: production
  RUST_LOG: INFO
  APP_SERVER__HOST: "0.0.0.0"
  APP_SERVER__PORT: "7777"
  APP_SERVER__METRICS_PATH: /metrics/game.prom
  APP_SERVER__ENABLE_AGONES: "true"
  APP_TRACING__OTEL_EXPORTER_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
