apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./assets-config.yml
  - ./external-dns.yml
  - ./game-server-config.yml
  - ./ingress.yml
  - ./mmo-server-deployment.yml
  - ./namespace.yml
  - ./web-server-deployment.yml
