apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns.yml
  - game-server-config.yml
  - ingress.yml
  - mmo-server-deployment.yml
  - secrets.yml
  - web-server-deployment.yml
