apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    email: rick.deboer@live.nl
    # The server is replaced in /clusters/<environment>/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - selector:
          dnsZones:
            - 'rejdeboer.com'
        dns01:
          cnameStrategy: Follow
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami
  namespace: default
spec:
  secretName: whoami-tls-app
  dnsNames:
    - "mmo.rejdeboer.com"
    - "mmo-provisioner.rejdeboer.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami
  namespace: monitoring
spec:
  secretName: whoami-tls-monitoring
  dnsNames:
    - "grafana.rejdeboer.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

