apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./provisioner.yml
patches:
  - path: patches/game-server-config-patch.yml
    target:
      kind: ConfigMap
      name: game-server-config
images:
  - name: rejdeboer/mmo-server
    newName: rejdeboer/mmo-server # {"$imagepolicy": "flux-system:mmo-server:name"}
    newTag: main-ff6b838-1764969416 # {"$imagepolicy": "flux-system:mmo-server:tag"}
  - name: rejdeboer/web-server
    newName: rejdeboer/web-server # {"$imagepolicy": "flux-system:web-server:name"}
    newTag: main-ff6b838-1764970041 # {"$imagepolicy": "flux-system:web-server:tag"}
