apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/assets-config.yml
  - ../base/db-seeder.yml
  - ../base/external-dns.yml
  - ../base/game-server-config.yml
  - ../base/ingress.yml
  - ../base/mmo-server-deployment.yml
  - ../base/secrets.yml
  - ../base/web-server-deployment.yml
patches:
- path: patches/game-server-config-patch.yml
  target:
    kind: ConfigMap
    name: game-server-config
- path: patches/mmo-server-deployment-patch.yml
  target:
    kind: Fleet
    name: mmo-server
- path: patches/web-server-deployment-patch.yml
  target:
    kind: Deployment
    name: web-server
