apiVersion: v1
kind: Service
metadata:
  name: mmo-provisioner
  namespace: default
  labels:
    app: mmo-provisioner
spec:
  ports:
    - name: mmo-provisioner
      port: 80
      targetPort: 8032
      protocol: TCP
  selector:
    app: mmo-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmo-provisioner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmo-provisioner
  template:
    metadata:
      labels:
        app: mmo-provisioner
    spec:
      containers:
        - name: mmo-provisioner
          image: rejdeboer/mmo-provisioner:main-6678488-1763676655 # {"$imagepolicy": "flux-system:mmo-provisioner"}
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8032
          env:
            - name: PROVISIONER_DATABASE_PORT
              value: "5432"
            - name: PROVISIONER_DATABASE_NAME
              value: "mmo"
            - name: PROVISIONER_DATABASE_HOST
              value: "postgres-main-rw"
            - name: PROVISIONER_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: PROVISIONER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: PROVISIONER_SERVER_HOST
              value: "0.0.0.0"
            - name: PROVISIONER_SERVER_PORT
              value: "8032"
            - name: PROVISIONER_SERVER_NETCODE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: netcode-secret
                  key: private-key
---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: mmo-provisioner
#   namespace: default
# spec:
#   entryPoints:
#     - websecure # Assumes you are using the 'websecure' entrypoint for HTTPS
#   routes:
#   - match: Host(`mmo-provisioner.rejdeboer.com`)
#     kind: Rule
#     services:
#     - name: mmo-provisioner
#       port: 80
#   tls:
#     secretName: whoami-tls-app
#     domains:
#     - main: "mmo-provisioner.rejdeboer.com"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mmo-provisioner
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: mmo-provisioner.rejdeboer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mmo-provisioner
                port:
                  number: 80
  tls:
    - hosts:
        - mmo-provisioner.rejdeboer.com
      secretName: whoami-tls-app

