apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  # - alloy.yml
  - k8s-monitoring.yml
  # - kube-prometheus-stack
  - loki.yml
  # - mimir.yml
  - repository.yml
  - tempo.yml
