apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: mmo-server
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - name: mmo-server
              image: mmo-server:main-74bc879-1763324843  # {"$imagepolicy": "flux-system:mmo-server"}
